# Generated by Django 5.2.1 on 2025-06-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_bfile_alter_customer_bfile2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ntcnk',
            new_name='ntchk',
        ),
    ]
