# Generated by Django 5.2.1 on 2025-05-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('hobby', models.CharField(blank=True, max_length=100)),
                ('sdate', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
