# Generated by Django 5.2.1 on 2025-05-27 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 27, 11, 37, 38, 580983)),
        ),
    ]
