# Generated by Django 5.2.1 on 2025-05-27 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 27, 12, 11, 58, 393120)),
        ),
    ]
