# Generated by Django 5.2.1 on 2025-06-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
    ]
