# Generated by Django 5.2.1 on 2025-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_address3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
