# Generated by Django 5.2.1 on 2025-06-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='btcnk',
            new_name='ntcnk',
        ),
    ]
